---
version: '3.8'

services:
  mysql-db:
    build:
      context: ./database
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tea_stall
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tea_stall
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    networks:
      - mdsurem_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - mdsurem_network

networks:
  mdsurem_network:
    driver: bridge

